### ISSUE TITLE
Empty LABEL param breaks vcard import in Thunderbird

### ISSUE THREAD

**Issue by lop-cz** [enesser/vCards-js#11]
Empty value of LABEL parameter (v4 format) should not be outputted in getFormattedAddress function otherwise it completely breaks import of vcard file in Thunderbird address book.
Importing is fine if LABEL contains some text. But empty values should not be outputted anyway.

**Comment by enesser** [comment]
This should be resolved now. Also the default vCard version is now 3.0. The 4.0 format is still not very well supported almost anywhere.

**Comment by lop-cz** [comment]
Thanks for all the corrections. But there is still small typo in v4 address formatter: the closing double quote character for LABEL parameter is left outside the related condition.
I know how this tiny typos could be irritating ;-)

**Comment by enesser** [comment]
Clumsy. Thanks so much.
