### ISSUE TITLE
New property for WORK URL

### ISSUE THREAD

**Issue by lop-cz** [enesser/vCards-js#12]
A new property for URL;TYPE=WORK would be helpful since the current untyped URL vCard property is mainly used for personal website and not the business/work website. 
It would also solve the problem when someone wants to have both personal and work websites included in a vcard.
New 'workUrl' object property could be introduced for this but it's just my suggestion.

**Comment by enesser** [comment]
Added this feature and added your name to the list of contributors. Thanks for the help.

**Comment by kennethbrent** [comment]
Is there anyway to add custom URLS opposed to just a 'work' URL? Custom Social Links are not detected as URLS and do not work unless its one of the preset options(flickr, linkedin, facebook) on IOS or android. I'm trying to add a URL for the users youtube channel, and the only current solution is to list it as their work url...when isn't necessarily correct.
