### ISSUE TITLE
TypeError: Object 98366 has no method 'replace'

### ISSUE THREAD

**Issue by vacarsu** [enesser/vCards-js#14]
I get this error when using workAddress fields.

**Comment by enesser** [comment]
I wonder if you don't have strings in your address fields. What does your address code look like?

**Comment by vacarsu** [comment]
They are string, are they not supposed to be?

**Comment by enesser** [comment]
They should be strings. Try out the example code in the README or look at the unit test:
https://github.com/enesser/vCards-js/blob/master/test/tests.js

**Comment by vacarsu** [comment]
I found the problem I was setting the city code to be a number instead of a string

**Comment by enesser** [comment]
Added code to convert other data types into a string in the encode method, because this sounds like a mistake that others will experience.

Thanks.
