### ISSUE TITLE
How can i create one Vcard using many Json objects?

### ISSUE THREAD

**Issue by AP25** [enesser/vCards-js#17]
I can create one Vcard(vcf file) from one object.
But I want to create one Vcard(vcf file) from multiple objects.
e.g :
I have 3 Json objects such as
[ { N: 'Stenerson,Derik',
    FN: 'Derik Stenerson',
    ORG: 'Microsoft Corporation',
    TITLE: '',
    PHOTO: { TYPE: '', PHOTO: '' },
    TEL: [ [Object], [Object] ],
    ADR: [],
    EMAIL: 'deriks@Microsoft.com' },
  { N: 'Ganguly,Anik',
    FN: 'Anik Ganguly',
    ORG: ' Open Text Inc.',
    TITLE: '',
    PHOTO: { TYPE: '', PHOTO: '' },
    TEL: [ [Object] ],
    ADR: [],
    EMAIL: 'ganguly@acm.org' },
  { N: 'Moskowitz,Robert',
    FN: 'Robert Moskowitz',
    ORG: '',
    TITLE: '',
    PHOTO: { TYPE: '', PHOTO: '' },
    TEL: [],
    ADR: [],
    EMAIL: 'rgm-ietf@htt-consult.com' } ]

and want to create one Vcard such as Xyz.vcf then how to create it ?

Thanks in advance

**Comment by enesser** [comment]
Thanks for asking.

I'm leaving this issue open because I am probably going to make an enhancement to the framework that will let you do this in a very easy way. However, until then, I will show you how you can do it with a workaround.

Per your example:

```js

'use strict';

var contacts = [{
    N: 'Stenerson,Derik',
    FN: 'Derik Stenerson',
    ORG: 'Microsoft Corporation',
    EMAIL: 'deriks@Microsoft.com'
}, {
    N: 'Ganguly,Anik',
    FN: 'Anik Ganguly',
    ORG: ' Open Text Inc.',
    EMAIL: 'ganguly@acm.org'
}, {
    N: 'Moskowitz,Robert',
    FN: 'Robert Moskowitz',
    ORG: '',
    EMAIL: 'rgm-ietf@htt-consult.com'
}];

var vCard = require('vcards-js');
var vContact;
var formattedString = '';

var vCards = contacts.forEach(function(contact) {
	vContact = vCard();
	vContact.firstName = contact.FN.split(',')[1];
	vContact.lastName = contact.FN.split(',')[0];
	vContact.organization = contact.ORG;
	vContact.email = contact.EMAIL;
	formattedString += vContact.getFormattedString();
});

var fs = require('fs');
fs.writeFileSync('xyz.vcf', formattedString, { encoding: 'utf8' });
```

**Comment by AP25** [comment]
Thanks Enesser !!!!
