### ISSUE TITLE
attachFromUrl not working in Mac contacts?

### ISSUE THREAD

**Issue by Bramzor** [enesser/vCards-js#20]
Class working create except for the attachFormUrl function.
Added this with vCard.photo.attachFromUrl('https://avatars2.githubusercontent.com/u/5659221?v=3&s=460', 'JPEG'); but is not shown in Contacts on Mac.
Is this a known issue?

**Comment by enesser** [comment]
I have had problems with the *attachFromUrl* function and Mac. I'm not sure it allows linking to images. I'll do some further testing and potentially list it as a known issue.

What does work -- and what I just recently tested -- is *embedFromFile*. Hopefully you can use that instead.
