### ISSUE TITLE
Don't use new Array()

### ISSUE THREAD

**Issue by adius** [enesser/vCards-js#27]
If somebody (me) stores e.g. the `cellPhone` as a number, it will crash the whole formatter.
(https://github.com/enesser/vCards-js/blob/master/lib/vCardFormatter.js#L223) as it means you're trying to generate an array with a certain size which can lead to errors if the range is too large.

E.g. `new Array(12345678900)` will throw following error:

```
RangeError: Invalid array length
    at Object.getFormattedString (/Project/node_modules/vcards-js/lib/vCardFormatter.js:254:39)
    at Object.getFormattedString (/Project/node_modules/vcards-js/index.js:321:35)
    ...
```

So `vCard.cellPhone = new Array(vCard.cellPhone);` should be replaced with `vCard.cellPhone = [vCard.cellPhone];`

**Comment by enesser** [comment]
Thank you! Added to next version.
