### ISSUE TITLE
Support for Social profile

### ISSUE THREAD

**Issue by fvisticot** [enesser/vCards-js#3]
Would be really great to add social profile !

X-SOCIALPROFILE;type=twitter:http://twitter.com/joebloggs

More info:
http://alessandrorossini.org/2012/11/15/the-sad-story-of-the-vcard-format-and-its-lack-of-interoperability/

**Comment by enesser** [comment]
Great suggestion. I'll get to it soon.

**Comment by fvisticot** [comment]
Thx, it will be very useful for my project !!

Regards

Fred

**Comment by enesser** [comment]
It's implemented in v1.0. Thanks for the suggestion.
