### ISSUE TITLE
Birthday in examples gives invalid date

### ISSUE THREAD

**Issue by AMongeMoreno** [enesser/vCards-js#32]
First, thank you for the work, it really helps so keep it up =D. 
I have found though that when using the example in the readme, the birthday date is not valid for javascript. Just update new Date('01-01-1985') to new Date(1985, 1, 1) =D

**Comment by enesser** [comment]
Hi!

I didn't have this issue in Node v8.6.0, but I can see how different browsers might parse strings differently so I decided to update the README all the same. Thanks for reporting!
