### ISSUE TITLE
Documentation issue causes "TypeError: vCard is not a function"

### ISSUE THREAD

**Issue by mbain** [enesser/vCards-js#33]
The example code in the documentation on the npm page causes an error in Node 8.  The line:
`vCard = vCard()` causes:
`TypeError: vCard is not a function`.
Changing it to something like `userVCard = vCard()` fixes the issue.

**Comment by enesser** [comment]
Really? Haven't gotten this in Node 8, and Travis CI tests pass. Are you using TypeScript or any other special settings? 

Thanks!

**Comment by enesser** [comment]
Although Travis tests use a different variable, let me check on that.

Thanks.

**Comment by mbain** [comment]
No TypeScript.  Just Node.js 8.14.0 running on Firebase.

**Comment by enesser** [comment]
Addressed in v2.10.0. Thanks!
