### ISSUE TITLE
How to generate as QR Code?

### ISSUE THREAD

**Issue by agungwiseso** [enesser/vCards-js#35]
Hi, i want to create QR as VCard like https://www.the-qrcode-generator.com/ in expressjs. Can we do that?

Thanks

**Comment by dtmzr** [comment]
There are other libraries like [qrcode](https://github.com/soldair/node-qrcode) which create qr codes through given data. I guess implementing that feature should be up to your application's business logic and not up to this library.

@enesser what're your two cents to this?

**Comment by enesser** [comment]
@agungwiseso @dtmzr Love the idea of using QR codes with vCards. But I do think it's probably best for application logic. Reason being, I think most built-in QR code readers simply take the user to a link after scanning from their native mobile camera app. But this would be a great idea for a SaaS solution where someone can create vCards with an online service and automatically get a QR code back.

You can easily use the Express example in the README to hook up a vCard to a URL, then a QR code to point to that URL. 
https://github.com/enesser/vCards-js#on-the-web

Let me know how it goes!

**Comment by dtmzr** [comment]
A few students from my course at university and I had to write a paper about cross-media business cards. We ended up with a solution where we print a qr code with a link to an endpoint on the business card. This link creates dynamically a vCard (using this library) from data from our database. The initial creator of the vCard can change the deposited data at any time, making the data on the business card "flexible". 

This project is based on express, mongo, mongoose, and vCards-js. If you're interested I could extract that logic and create a simple real-world example for this library? 

Maybe even with both ideas, dynamically data and static.

**Comment by enesser** [comment]
@dtmzr Sounds like a great project. I would love that. Thanks!

**Comment by dtmzr** [comment]
@enesser [here](https://github.com/dtmzr/vCard-app) you go.
It's under MIT so anyone can use it however they want to.
Surely would like to here your two cents on that! 👍

Would you like to be added as a collaborator?
Gonna suggest this as an example on the QR code library too.

**Comment by enesser** [comment]
@dtmzr Very cool! Gonna check it out soon and possibly link to it from this project, if that's okay!

**Comment by dtmzr** [comment]
@enesser Sure, whatever you like. Guess this here can be closed then.
