### ISSUE TITLE
Create a JavaScript code for a PDF button to import vCards contacts into  iOS and Android devices when open on samrt phone

### ISSUE THREAD

**Issue by Nour-eldeen-Mahmoud** [enesser/vCards-js#42]
Hello guys,
Can anyone help me in this:
I have PDF file with phone number in it and the client wants me make it clickable and leads to saving a contact info in the mobile contacts.
using adobe acrobat I can make buttons and give them actions when pressed, one of the actions options in Adobe acrobat is to "run JavaScript" but I can't write the proper code for it 
Thanks a lot

**Comment by enesser** [comment]
Might be best to try to link out from the PDF to a website that has this functionality. Is that a possibility?

**Comment by Nour-eldeen-Mahmoud** [comment]
> Might be best to try to link out from the PDF to a website that has this functionality. Is that a possibility?

Ya man I figured it out, it is the best way to do so, thanks a lot for your help really appreciate it.

**Comment by enesser** [comment]
Cool. Thanks for the update!
