### ISSUE TITLE
Parsing of vCard files

### ISSUE THREAD

**Issue by maxnowack** [enesser/vCards-js#5]
Is it planned to support parsing vCard files?

**Comment by enesser** [comment]
It's planned, but not yet implemented. There's a few other libraries out there that parse vCards. 

I haven't tried any of these yet.
https://www.npmjs.com/package/vcardparser
https://www.npmjs.com/package/oniyi-vcard-parser
https://github.com/nilclass/vcardjs

**Comment by nasht00** [comment]
I guess this is only useful if those other libraries share the exact same naming conventions than yours...
