### ISSUE TITLE
Can i use in browser with frontend only.

### ISSUE THREAD

**Issue by jitendra1607** [enesser/vCards-js#54]
Can i use in browser with frontend only.

**Comment by NiklasAkita** [comment]
Yes, for now at least, i have luck using it on a website. 
But you can't use the built in download functionality since it is based on a backend library.

**Comment by Toumash** [comment]
@jitendra1607 @NiklasAkita do any of you guys have a working demo?

**Comment by jitendra1607** [comment]
> @jitendra1607 @NiklasAkita do any of you guys have a working demo?
fn - firstname
mn - middlename
ln- lastname


`
 var vcf = `BEGIN:VCARD\nVERSION:3.0\nFN;CHARSET=UTF-8:${firstname} ${middlename} ${lastname}\nN;CHARSET=UTF-8:${lastname};${firstname};${middlename};;\nEMAIL;CHARSET=UTF-8;type=HOME,INTERNET:${email}\nTEL;TYPE=HOME,VOICE:${mobile_number}\nTEL;TYPE=WORK,VOICE:${mobile_number2}\nLABEL;CHARSET=UTF-8;TYPE=WORK:${address}\nADR;CHARSET=UTF-8;TYPE=WORK:;;;;;;\nROLE;CHARSET=UTF-8:${dt.d}\nORG;CHARSET=UTF-8:${dt.o}\nURL;type=WORK;CHARSET=UTF-8:${dt.w}\nREV:2020-08-31T03:41:09.870Z\nEND:VCARD`;
                  var imgqr = document.getElementById('qr');
                  imgqr.src = 'https://chart.googleapis.com/chart?cht=qr&chs=340x340&chl=' + vcf.replace(/\n/g,'%0A');
`

**Comment by Imperio8** [comment]
This is my solution to download it as a file:

```
import vCardsJS from 'vcards-js';

const download = (vCardString, fileName) => {
	let fileURL = window.URL.createObjectURL(new Blob([vCardString]));
	let fileLink = document.createElement('a');
	fileLink.href = fileURL;
	fileLink.setAttribute('download', `${fileName}.vcf`);
	document.body.appendChild(fileLink);
	fileLink.click();
};

const generateVCard= (contact) => {
       	//Map the data here accordingly
	vCard.firstName = contact.name;
	
	//Add Other data as listed on documentation
	
	//Stringify it
	const formattedString = vCard.getFormattedString()
	download(formattedString , `filename`);
}
```

This should work in any js file. I hope this helps :)

**Comment by Toumash** [comment]
This issue can be closed :)
