### ISSUE TITLE
Charset support for accent

### ISSUE THREAD

**Issue by fvisticot** [enesser/vCards-js#6]
I'm using your lib for a french application and I need support for accent.
After some tests, it seems that adding the charset in the vcard solve my pb.
Do you think it is possible to add the charset support in your lib to able to display accents as described in the following sample:

BEGIN:VCARD
VERSION:4.0
FN:frédéric
N;CHARSET=utf-8;:;pêché;;;
X-SOCIALPROFILE;CHARSET=utf-8;TYPE=twitter:http://www.twitter.com/frédéric
X-SOCIALPROFILE;TYPE=skype:S12345
REV:2015-05-18T21:43:30+00:00
END:VCARD

**Comment by enesser** [comment]
Thanks! I'll get this patched over the weekend.

**Comment by fvisticot** [comment]
Hello,
Did you had time to make the patch.
I’m very excited to test this new feature !

Regards

**Comment by enesser** [comment]
There is a new release. Give it a shot.

Thanks.
