### ISSUE TITLE
Attaching photo from Url

### ISSUE THREAD

**Issue by fvisticot** [enesser/vCards-js#7]
Is the documentation always valid from your sample code ?

vCard.photo.attachFromUrl('https://avatars2.githubusercontent.com/u/5659221?v=3&s=460', 'JPEG');

I was thinking we can directly use:
vCard.photo.url

Can you please clarify ?

**Comment by enesser** [comment]
As an alternative, you can also do the following:

vCard.photo.url = 'https://avatars2.githubusercontent.com/u/5659221?v=3&s=460';
vCard.photo.mediaType = 'JPEG';
