### ISSUE TITLE
Embed photo directly as base64 ?

### ISSUE THREAD

**Issue by fvisticot** [enesser/vCards-js#8]
Is it possible with this library to embed the photo itself as a base64 content in the vcard ?

**Comment by enesser** [comment]
I'll amend the documentation since this is a newer feature I haven't documented yet, but to attach a photo or a logo using base64 encoding, you'd do this:

vCard.photo.embedFromFile('c:\\path\\file.png');
vCard.logo.embedFromFile('c:\\path\\file.png');

**Comment by fvisticot** [comment]
Works great !!!

Tx
